"""
Analytics Workbench — Web Installation Wizard.

Rendered automatically by app.py when the .installed lock file is absent.
Four steps:
  1  Requirements  — checks Python version, libraries, and dir write permissions
  2  Configuration — site name, database path, initial admin credentials
  3  Installation  — writes .env, creates schema, creates admin account
  4  Complete      — success screen with "Launch App" button
"""
from __future__ import annotations

import importlib
import os
import secrets
import sqlite3
import sys
import time
from pathlib import Path

import streamlit as st

_ROOT = Path(__file__).parent.parent

# ── Required packages ─────────────────────────────────────────────────────────
# (display_name, import_name, min_version_hint)
REQUIRED_PACKAGES: list[tuple[str, str, str]] = [
    ("streamlit",     "streamlit",    "1.28"),
    ("pandas",        "pandas",       "1.3"),
    ("numpy",         "numpy",        "1.21"),
    ("scikit-learn",  "sklearn",      "1.0"),
    ("bcrypt",        "bcrypt",       "3.0"),
    ("cryptography",  "cryptography", "38.0"),
    ("python-dotenv", "dotenv",       "0.19"),
    ("Pillow",        "PIL",          "8.0"),
    ("PyTorch",       "torch",        "1.11"),
]

# Directories that must be writable
WRITE_DIRS: list[tuple[str, str]] = [
    ("data/",         "SQLite database storage"),
    ("session_data/", "Streamlit session persistence"),
    ("logs/",         "Application logs"),
    ("static/",       "Uploaded assets (logos, etc.)"),
]

# ── Requirement checks ────────────────────────────────────────────────────────

def _check_python() -> tuple[bool, str]:
    v = sys.version_info
    return (v.major, v.minor) >= (3, 9), f"{v.major}.{v.minor}.{v.micro}"


def _check_package(import_name: str) -> tuple[bool, str]:
    try:
        mod = importlib.import_module(import_name)
        ver = getattr(mod, "__version__", None) or getattr(mod, "version", "installed")
        return True, str(ver)
    except ImportError:
        return False, "not installed"


def _check_writable(rel: str) -> tuple[bool, str]:
    p = _ROOT / rel
    try:
        p.mkdir(parents=True, exist_ok=True)
        probe = p / ".write_test"
        probe.write_text("ok")
        probe.unlink()
        return True, "writable"
    except Exception as exc:
        return False, str(exc)


def _all_requirements_ok() -> bool:
    if not _check_python()[0]:
        return False
    for _, imp, _ in REQUIRED_PACKAGES:
        if not _check_package(imp)[0]:
            return False
    for d, _ in WRITE_DIRS:
        if not _check_writable(d)[0]:
            return False
    return True


# ── Installation helpers ──────────────────────────────────────────────────────

def _env_file() -> Path:
    """Return the path to write/read the env config file.

    Prefers .env, but falls back to app.env when .env is a directory
    (e.g. when the old-style Python venv lives at .env/).
    admin/db.py tries both names so the app loads whichever exists.
    """
    candidate = _ROOT / ".env"
    if candidate.is_dir():
        return _ROOT / "app.env"
    return candidate


def _write_env(cfg: dict) -> None:
    """Write the env config file from the configuration dict collected in Step 2."""
    lines = [
        "# Analytics Workbench — Environment Configuration",
        "# Generated by the installation wizard.",
        "# Keep this file secret. Do NOT commit it to version control.",
        "",
        f'APP_NAME="{cfg["site_name"]}"',
        "APP_ENV=production",
        "APP_DEBUG=false",
        f'APP_URL={cfg["app_url"]}',
        f'APP_SECRET_KEY={cfg["secret_key"]}',
        "",
        "# SQLite database (leave blank to use default: data/analytics_workbench.db)",
        f'DB_PATH={cfg["db_path"]}',
        "DB_PREFIX=aw_",
        "",
        "STREAMLIT_SERVER_PORT=8501",
        "STREAMLIT_SERVER_ADDRESS=0.0.0.0",
        "STREAMLIT_SERVER_HEADLESS=true",
        "STREAMLIT_BROWSER_GATHER_USAGE_STATS=false",
        "",
        "# Initial superadmin — used during first-launch seeding only",
        f'ADMIN_EMAIL={cfg["admin_email"]}',
        f'ADMIN_PASSWORD={cfg["admin_password"]}',
    ]
    _env_file().write_text("\n".join(lines) + "\n")


def _reload_env() -> None:
    """Push the freshly written env file into the current process's environment."""
    try:
        from dotenv import load_dotenv
        load_dotenv(_env_file(), override=True)
    except ImportError:
        pass  # dotenv unavailable — values were set manually via os.environ


def _create_dirs() -> None:
    for d, _ in WRITE_DIRS:
        (_ROOT / d).mkdir(parents=True, exist_ok=True)


def _test_db(db_path: str) -> None:
    """Verify SQLite can open (or create) the target database file."""
    p = Path(db_path) if db_path else _ROOT / "data" / "analytics_workbench.db"
    p.parent.mkdir(parents=True, exist_ok=True)
    conn = sqlite3.connect(str(p))
    conn.execute("SELECT 1")
    conn.close()


def _run_schema(db_path: str) -> None:
    """Bootstrap all admin tables (idempotent)."""
    if db_path:
        os.environ["DB_PATH"] = db_path
    from admin.db import ensure_admin_schema
    ensure_admin_schema()


def _create_admin(email: str, password: str, name: str, db_path: str) -> None:
    """Insert the superadmin row, replacing any existing one with the same email."""
    if db_path:
        os.environ["DB_PATH"] = db_path
    import bcrypt
    from admin.db import get_db
    prefix = os.environ.get("DB_PREFIX", "aw_")
    hashed = bcrypt.hashpw(password.encode(), bcrypt.gensalt(12)).decode()
    with get_db() as (_, cur):
        cur.execute(
            f'INSERT OR REPLACE INTO "{prefix}users" '
            f'(name, email, password, role) VALUES (?, ?, ?, "superadmin")',
            (name, email, hashed),
        )


def _write_lock() -> None:
    """Write the .installed flag so the wizard is never shown again."""
    (_ROOT / ".installed").write_text(
        f"installed_at={time.strftime('%Y-%m-%dT%H:%M:%S')}\nversion=1.0.0\n"
    )


# ── Shared page chrome ────────────────────────────────────────────────────────

_CSS = """
<style>
/* Wizard backdrop */
[data-testid="stAppViewContainer"] > .main {
    background: #0f172a;
}
/* Hero header */
.wiz-hero {
    text-align: center;
    padding: 2.5rem 0 0.5rem;
}
.wiz-hero h1 {
    font-size: 2rem;
    font-weight: 800;
    color: #f1f5f9;
    letter-spacing: -.02em;
    margin: 0;
}
.wiz-hero p {
    color: #94a3b8;
    margin-top: .4rem;
    font-size: .95rem;
}
/* Step progress bar */
.step-bar {
    display: flex;
    gap: 0;
    margin: 1.5rem 0 0;
    border-radius: 8px;
    overflow: hidden;
}
.step-item {
    flex: 1;
    text-align: center;
    padding: .55rem .25rem;
    font-size: .78rem;
    font-weight: 700;
    letter-spacing: .02em;
    text-transform: uppercase;
    border-bottom: 3px solid transparent;
}
.step-done { color: #22c55e; border-color: #22c55e; }
.step-curr { color: #60a5fa; border-color: #60a5fa; background: rgba(96,165,250,.07); }
.step-todo { color: #475569; border-color: #1e293b; }
/* Status icons in results */
.ok   { color: #22c55e; font-weight: 700; }
.fail { color: #ef4444; font-weight: 700; }
</style>
"""


def _page_chrome() -> None:
    st.markdown(_CSS, unsafe_allow_html=True)
    st.markdown(
        "<div class='wiz-hero'>"
        "<h1>⚙️ Analytics Workbench</h1>"
        "<p>Installation Wizard — configure your instance in a few steps.</p>"
        "</div>",
        unsafe_allow_html=True,
    )


def _progress_bar(current: int) -> None:
    labels = ["1 · Requirements", "2 · Configuration", "3 · Install", "4 · Complete"]
    parts = []
    for i, label in enumerate(labels, 1):
        if   i < current:  cls = "step-done"; icon = "✓ "
        elif i == current: cls = "step-curr"; icon = "● "
        else:              cls = "step-todo"; icon = "○ "
        parts.append(f"<div class='step-item {cls}'>{icon}{label}</div>")
    st.markdown("<div class='step-bar'>" + "".join(parts) + "</div>",
                unsafe_allow_html=True)
    st.markdown("---")


# ── Step 1: Requirements ──────────────────────────────────────────────────────

def _step1_requirements() -> None:
    st.subheader("Step 1 — Server Requirements")
    st.caption("Verifying your environment meets all prerequisites before installation.")

    any_fail = False

    # Python version
    py_ok, py_ver = _check_python()
    if not py_ok:
        any_fail = True
    st.markdown("**Python Interpreter**")
    if py_ok:
        st.success(f"Python {py_ver} ✓  (requires ≥ 3.9)")
    else:
        st.error(f"Python {py_ver} — version 3.9 or newer is required.")

    # Required libraries
    st.markdown("**Required Libraries**")
    import pandas as pd
    lib_rows = []
    for display, imp, min_v in REQUIRED_PACKAGES:
        ok, ver = _check_package(imp)
        if not ok:
            any_fail = True
        lib_rows.append({
            "Package":     display,
            "Installed":   ver,
            "Min Version": f"≥ {min_v}",
            "Status":      "✅" if ok else "❌",
        })
    st.dataframe(pd.DataFrame(lib_rows), use_container_width=True, hide_index=True)

    # Directory permissions
    st.markdown("**Directory Write Permissions**")
    dir_rows = []
    for rel, purpose in WRITE_DIRS:
        ok, msg = _check_writable(rel)
        if not ok:
            any_fail = True
        dir_rows.append({
            "Directory": rel,
            "Purpose":   purpose,
            "Status":    f"✅  {msg}" if ok else f"❌  {msg}",
        })
    st.dataframe(pd.DataFrame(dir_rows), use_container_width=True, hide_index=True)

    st.markdown("")
    if any_fail:
        st.error(
            "One or more requirements are not met.  \n"
            "• Install missing packages: `pip install -r requirements.txt`  \n"
            "• Ensure the listed directories are writable by the server process."
        )
        if st.button("🔄 Re-check", use_container_width=True, key="s1_recheck"):
            st.rerun()
    else:
        st.success("All requirements satisfied — ready to continue.")
        if st.button("Continue →", type="primary", use_container_width=True, key="s1_next"):
            st.session_state.wiz_step = 2
            st.rerun()


# ── Step 2: Configuration ─────────────────────────────────────────────────────

def _step2_configuration() -> None:
    st.subheader("Step 2 — Configuration")
    st.caption("Enter your site settings and create the initial administrator account.")

    saved = st.session_state.get("wiz_cfg", {})

    with st.form("wiz_cfg_form", clear_on_submit=False):

        st.markdown("#### Application")
        c1, c2 = st.columns(2)
        site_name = c1.text_input(
            "Site Name *",
            value=saved.get("site_name", "Analytics Workbench"),
        )
        app_url = c2.text_input(
            "App URL",
            value=saved.get("app_url", "http://localhost"),
            help="The public URL where this instance will be accessible.",
        )

        st.markdown("#### Database")
        db_path = st.text_input(
            "SQLite Database Path",
            value=saved.get("db_path", ""),
            placeholder="Leave blank — default: data/analytics_workbench.db",
            help=(
                "Absolute path to the SQLite .db file. "
                "Leave blank to use the built-in default location."
            ),
        )

        st.markdown("#### Administrator Account")
        c3, c4 = st.columns(2)
        admin_name  = c3.text_input("Full Name *",  value=saved.get("admin_name",  "Admin"))
        admin_email = c4.text_input(
            "Email Address *",
            value=saved.get("admin_email", ""),
            placeholder="admin@example.com",
        )
        c5, c6 = st.columns(2)
        admin_pass  = c5.text_input("Password *",         type="password", value="",
                                    help="Minimum 8 characters.")
        admin_pass2 = c6.text_input("Confirm Password *", type="password", value="")

        col_back, col_spacer, col_next = st.columns([1, 0.3, 3])
        go   = col_next.form_submit_button("Continue →", type="primary",
                                           use_container_width=True)
        back = col_back.form_submit_button("← Back", use_container_width=True)

    if back:
        st.session_state.wiz_step = 1
        st.rerun()

    if go:
        errs: list[str] = []
        if not site_name.strip():
            errs.append("Site Name is required.")
        if not admin_name.strip():
            errs.append("Admin Full Name is required.")
        if not admin_email.strip() or "@" not in admin_email:
            errs.append("A valid Admin Email address is required.")
        if len(admin_pass) < 8:
            errs.append("Password must be at least 8 characters.")
        if admin_pass != admin_pass2:
            errs.append("Passwords do not match.")
        if db_path.strip() and not Path(db_path.strip()).parent.exists():
            errs.append(
                f"Database parent directory does not exist: {Path(db_path.strip()).parent}"
            )

        if errs:
            for e in errs:
                st.error(e)
        else:
            st.session_state.wiz_cfg = {
                "site_name":      site_name.strip(),
                "app_url":        app_url.strip() or "http://localhost",
                "db_path":        db_path.strip(),
                "admin_name":     admin_name.strip(),
                "admin_email":    admin_email.strip(),
                "admin_password": admin_pass,
                "secret_key":     secrets.token_hex(32),
            }
            st.session_state.wiz_step = 3
            st.rerun()


# ── Step 3: Install ───────────────────────────────────────────────────────────

def _step3_install() -> None:
    st.subheader("Step 3 — Installation")

    cfg: dict | None = st.session_state.get("wiz_cfg")
    if not cfg:
        st.error("Configuration is missing — please complete Step 2 first.")
        if st.button("← Back to Configuration", key="s3_nocfg_back"):
            st.session_state.wiz_step = 2
            st.rerun()
        return

    # Already completed — skip forward
    if st.session_state.get("wiz_done"):
        st.session_state.wiz_step = 4
        st.rerun()
        return

    # Summary card
    st.markdown("Review the settings below, then click **Install Now** to proceed.")
    with st.expander("Configuration summary", expanded=True):
        c1, c2 = st.columns(2)
        c1.markdown(f"**Site Name:** {cfg['site_name']}")
        c1.markdown(f"**App URL:** {cfg['app_url']}")
        c1.markdown(f"**DB Path:** `{cfg['db_path'] or 'data/analytics_workbench.db  (default)'}`")
        c2.markdown(f"**Admin Name:** {cfg['admin_name']}")
        c2.markdown(f"**Admin Email:** {cfg['admin_email']}")
        c2.markdown("**Password:** *(hidden)*")

    col_back, _sp, col_install = st.columns([1, 0.3, 3])
    if col_back.button("← Back", key="s3_back", use_container_width=True):
        st.session_state.wiz_step = 2
        st.rerun()

    if not col_install.button("🚀 Install Now", type="primary", key="s3_go",
                               use_container_width=True):
        return

    # ── Run all installation steps with live feedback ─────────────────────────
    install_steps: list[tuple] = [
        ("Writing .env configuration file",              _write_env,      cfg),
        ("Loading environment variables",                _reload_env),
        ("Creating required directories",                _create_dirs),
        ("Testing database connection",                  _test_db,        cfg["db_path"]),
        ("Running database migrations",                  _run_schema,     cfg["db_path"]),
        (f"Creating admin account ({cfg['admin_email']})", _create_admin,
         cfg["admin_email"], cfg["admin_password"], cfg["admin_name"], cfg["db_path"]),
        ("Finalising installation",                      _write_lock),
    ]

    total    = len(install_steps)
    progress = st.progress(0, text="Starting…")
    log_area = st.container()
    results: list[tuple[bool, str]] = []
    failed   = False

    for idx, step in enumerate(install_steps, 1):
        label, fn, *args = step
        progress.progress(idx / total, text=label + "…")
        try:
            fn(*args)
            results.append((True, label))
        except Exception as exc:
            results.append((False, f"{label}: {exc}"))
            failed = True
            break

    progress.empty()

    with log_area:
        for ok, msg in results:
            if ok:
                st.markdown(f"✅ &nbsp; {msg}")
            else:
                st.markdown(f"❌ &nbsp; {msg}")

    if failed:
        st.error(
            "Installation failed at the step shown above. "
            "Fix the issue and click Install Now again."
        )
        return

    st.session_state.wiz_done = True
    time.sleep(0.4)
    st.session_state.wiz_step = 4
    st.rerun()


# ── Step 4: Complete ──────────────────────────────────────────────────────────

def _step4_complete() -> None:
    st.balloons()
    st.success("### ✅ Installation complete!")

    cfg = st.session_state.get("wiz_cfg", {})

    st.markdown(
        "**Analytics Workbench** has been installed and configured successfully. "
        "Click **Launch App** to go directly to the login screen."
    )
    st.markdown("---")

    col_info, col_next = st.columns(2)

    col_info.markdown("**Your login credentials**")
    col_info.markdown(f"- **Email:** `{cfg.get('admin_email', '')}`")
    col_info.markdown("- **Password:** *(as entered during setup)*")

    col_next.markdown("**Post-install checklist**")
    col_next.markdown(
        "- [ ] Log in and verify access  \n"
        "- [ ] Change your password in **Admin → Users**  \n"
        "- [ ] Review site settings in **Admin → Settings**  \n"
        "- [ ] Add external API keys in **Admin → API Keys**"
    )

    st.markdown("---")
    if st.button("🚀 Launch App", type="primary", use_container_width=True, key="s4_launch"):
        # Clear wizard state so it doesn't pollute the main app's session
        for k in list(st.session_state.keys()):
            if k.startswith("wiz_"):
                del st.session_state[k]
        # Rerun — app.py will find .installed and skip this wizard
        st.rerun()


# ── Public entry point ────────────────────────────────────────────────────────

def render_wizard() -> None:
    """Render the correct wizard step.  Called from app.py when .installed is absent."""
    _page_chrome()
    step: int = st.session_state.get("wiz_step", 1)
    _progress_bar(step)

    if   step == 1: _step1_requirements()
    elif step == 2: _step2_configuration()
    elif step == 3: _step3_install()
    elif step == 4: _step4_complete()
    else:
        st.session_state.wiz_step = 1
        st.rerun()
